# DB Setting
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cozycorner1.cafe24.com:3306/cozycorner1?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: cozycorner1
    password: cozy123!@

  #JPA Setting
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
server:
  port: 8011
